#!/bin/bash
#SBATCH -A dep # account
#SBATCH -n 2 # Number of cores
#SBATCH -N 1 # Ensure that all cores are on one machine
#SBATCH -D /ghome/mpilligua/lowlight/Models/MIRNet/ # working directory
#SBATCH -p dcca40 # Partition to submit to
#SBATCH --mem 4000 # 2GB solicitados.
#SBATCH -o %x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e %x_%u_%j.err # File to which STDERR will be written
#SBATCH --gres gpu:1 # Para pedir gráficas

python preprocess_mask_rcnn.py \ 
 --data-path /home/mpilligua/Video-Segmentation/Data/DAVIS/JPEGImages/480p/choreography \ 
 --class_name anything \
 --object_name anything